import type { Metadata } from "next";
import { Anonymous_Pro, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const font = Anonymous_Pro({
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Quantumflux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={font.className}
      >
        {children}
      </body>
    </html>
  );
}
